version: "3"
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=production
      - local_root=/web/current/app/storage/backup
      - dropbox_token=ceehOGvYBRMAAAAAAAAQwp7OzhQ62jTQ9UWtHbZiYsrG1g85T0mXAGDmmHdvNgPC
      - dropbox_key=y8wucaas8pwy081
      - dropbox_secret=ifmn03usntjppd5
      - mail_driver=smtp
      - mail_host=host196.hostmonster.com
      - mail_port=465
      - mail_from_address=noresponder@propar.com.py
      - mail_from_name='Inmobiliaria Propar'
      - mail_encryption=ssl
      - mail_username=noresponder@propar.com.py
      - mail_password=aQiMa44pPH
      - mysql_host=db
      - mysql_database=c1propar
      - mysql_username=root
      - mysql_password=1RsTD@GpShf9j
      - bancard_test_mode=false
      - bancard_public_key=zqgPuWNFsKsSb1tp0gSfWkQMvx621Z2z
      - bancard_private_key=bFURGbEOEMyon9bf+Qoz8VO1iMcAK.H.566rRw1b
      - shipping_default_delivery_time=24
      - cbi_api_uri=https://sistema.propar.com.py/api/
      - cbi_api_username=prueba_api
      - cbi_api_password=pruebaapi2017
    working_dir: /propar
    volumes:
      - ./:/propar
    command: "php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - 8001:8000

  #MySQL Service
  db:
    image: mysql:5
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "33062:3306"
    environment:
      - MYSQL_DATABASE=c1propar
      - MYSQL_ROOT_PASSWORD=1RsTD@GpShf9j
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf

#Volumes
volumes:
  dbdata:
    driver: local
